
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        # self.choose_method = QtWidgets.QComboBox(self.widget)
        # self.choose_method.setObjectName("choose_method")
        # self.choose_method.addItem("")
        # self.choose_method.addItem("")
        # self.choose_method.addItem("")
        # self.verticalLayout.addWidget(self.choose_method)
        self.open_mix1 = QtWidgets.QPushButton(self.widget)
        self.open_mix1.setObjectName("open_mix1")
        self.verticalLayout.addWidget(self.open_mix1)
        self.open_mix2 = QtWidgets.QPushButton(self.widget)
        self.open_mix2.setObjectName("open_mix2")
        self.verticalLayout.addWidget(self.open_mix2)
        self.Mixer_songs = QtWidgets.QSlider(self.widget)
        self.Mixer_songs.setOrientation(QtCore.Qt.Horizontal)
        self.Mixer_songs.setObjectName("Mixer_songs")
        self.verticalLayout.addWidget(self.Mixer_songs)
        self.percentagemix = QtWidgets.QLabel(self.widget)
        self.percentagemix.setObjectName("percentagemix")
        self.verticalLayout.addWidget(self.percentagemix)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.similarity_output = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.similarity_output.setFont(font)
        self.similarity_output.setObjectName("similarity_output")
        self.verticalLayout_2.addWidget(self.similarity_output)
        self.similarity_output_table = QtWidgets.QTableWidget(self.widget1)
        self.similarity_output_table.setObjectName("similarity_output_table")
        self.similarity_output_table.setColumnCount(2)
        self.similarity_output_table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.similarity_output_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.similarity_output_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.similarity_output_table)
        self.similarity_output_table.setColumnWidth(0, 500)
        self.show_results = QtWidgets.QPushButton(self.widget1)
        self.show_results.setObjectName("show_results")
        self.verticalLayout_2.addWidget(self.show_results)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpen_Songs = QtWidgets.QMenu(self.menubar)
        self.menuOpen_Songs.setObjectName("menuOpen_Songs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsong = QtWidgets.QAction(MainWindow)
        self.actionsong.setObjectName("actionsong")
        self.menuOpen_Songs.addAction(self.actionsong)
        self.menubar.addAction(self.menuOpen_Songs.menuAction())
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.similarity_output_table.setStyleSheet("background-image: url(y.jpg) ;background-repeat:no-repeat;background-position:center;")
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_mix1.setText(_translate("MainWindow", "open mix 1"))
        self.open_mix2.setText(_translate("MainWindow", "open mix 2"))
        self.percentagemix.setText(_translate("MainWindow", "percentage_mix"))
        self.similarity_output.setText(_translate("MainWindow", "Similarity Output"))
        item = self.similarity_output_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Song Name"))
        item = self.similarity_output_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Similarity (%)"))
        self.show_results.setText(_translate("MainWindow", "Show Results"))
        self.menuOpen_Songs.setTitle(_translate("MainWindow", "Open Song"))
        self.actionsong.setText(_translate("MainWindow", "song"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
